### ISSUE TITLE
[Request] Display currently playing song in Mixtape menu

### ISSUE THREAD

**Issue by teleheel** [UnJust1ce/Mixtape#11]
It would be awesome if you could display which song is currently playing, as an alternative to having the toasts always on. You could for example have a line dedicated to "Now playing: ..." in the mod's menu, but it's up to you of course!

**Comment by AliahX** [comment]
Thanks for making a request! There's already an option in the music toasts section to show a now playing message where jukebox songs normally show up, and an option to make the toast/now playing message remain until the song finished. (just letting you know in case you didn't already) is there a specific place in the menu where you think it would fit?

**Comment by teleheel** [comment]
Yeah those options are great, but it would also be nice to have the possibility to look up the currently playing song without "cluttering" the HUD while playing.

Where to place it is a bit difficult though, I'm not very good with UI design :) Two possibilities I can think of are:

- As a greyed out line above the `Enabled` option in the main tab of the mod's config menu. The drawback of this is that it is kind of obscure, and most casual players might never stumble upon the feature.
- As a line of text somewhere on the Game Menu (i.e. when pressing escape), e.g. below the `Game Menu` text. This would make it really convenient to quickly check which song is playing, and would in my opinion be a cleaner, more natural way of incorporating it. Maybe you could add a config option for showing/hiding it?

**Comment by AliahX** [comment]
<img width="706" alt="Screen Shot 2023-07-21 at 11 40 04 AM" src="https://github.com/AliahX/Mixtape/assets/40045439/f8a506a4-1a2a-4ff5-8ec9-2e745ba044f6">
<img width="450" alt="Screen Shot 2023-07-21 at 11 59 17 AM" src="https://github.com/AliahX/Mixtape/assets/40045439/4643eefd-e5e9-4bbd-9dec-aea8c5aa9534">

Does this look good?
I've added options so you can choose where and if it shows up.

**Comment by teleheel** [comment]
Yes, that looks perfect!

**Comment by AliahX** [comment]
Awesome! This will be in the next update.

**Comment by AliahX** [comment]
added in v1.6.2
