### ISSUE TITLE
Game crashes when inserting a disk in the jukebox (mc1.20.1 mixtape 1.6.1)

### ISSUE THREAD

**Issue by Gamma120** [UnJust1ce/Mixtape#13]
Hi,
The game crashes when I'm inserting a disk in the jukebox, in Creative mode (didn't try in other modes). The song begins to play and the toast doesn't appear.

- Minecraft: 1.20.1
- Fabric Loader: 0.14.22
- Fabric API: 0.87.0
- YetAnotherConfigLib: 3.1.0
- Mixtape: 1.6.1

Here is the [crash-2023-09-02_16.50.25-client.txt](https://github.com/AliahX/Mixtape/files/12504216/crash-2023-09-02_16.50.25-client.txt) and Mixtape config [mixtape.txt](https://github.com/AliahX/Mixtape/files/12504205/mixtape.txt) (Github don't want to upload JSON).

Thanks for your mod

**Comment by AliahX** [comment]
Thanks for the report! ill look into it as soon as I can. Did you use any mods or resourcepacks that add songs or anything like that?

**Comment by Gamma120** [comment]
> Did you use any mods or resourcepacks that add songs or anything like that?

Yes, so at first I thought it was this but, I deactivated all the other mods and resourcepacks (on MultiMC) and had the same crashes. That why I opened this issue.

I have just done some tests with a fresh instance on MultiMC with only Mixtape, and I have encountered no problem. So it must be this.

**Comment by AliahX** [comment]
i'm able to reproduce the issue, i've got no idea how it happened or how i missed it lmao. ill work on fixing it as soon as I have time

**Comment by AliahX** [comment]
I've fixed this issue! the next version of mixtape will not have this issue anymore

**Comment by AliahX** [comment]
fixed in v1.6.2
