### ISSUE TITLE
Only C418 RP doesn't work

### ISSUE THREAD

**Issue by omoaubs** [UnJust1ce/Mixtape#15]
Whenever I use the only C418 music resource pack it still plays the newer songs. The unused song part of the pack works, but not the only C418 part. I've tried both packs. 

I'm using Minecraft 1.20.1, I have Mixtape 1.6.1 installed, I have minor GUI resource packs and the Fabric API resource pack installed.

**Comment by AliahX** [comment]
Are you using other resourcepacks along with it?

**Comment by omoaubs** [comment]
I’m using one for a GUI retexture, one for the voice chat mod retexture, one for the Fabric API, the default Minecraft one, and the resource pack in question.

**Comment by AliahX** [comment]
I can not reproduce this issue in the latest version. The resourcepack only changes music in the overworld, not the nether. if that is your problem you need to use the no nether update music.
