### ISSUE TITLE
Not playing music in 1.19.2 Version

### ISSUE THREAD

**Issue by Bris42** [UnJust1ce/Mixtape#17]
So I'm using the 1.19.2 version. The mod is properly installed, and the buttons are mapped out, but I cant control the music at all. I can alter the settings in its option page, but it doesn't actually alter anything. Actually, I've noticed that the music plays a lot less. Not to mention, the resource packs to remove tracks aren't compatible with the version itself.

**Comment by AliahX** [comment]
did u go into the settings and turn the mod on? for some reason i decided to have it off by default... that will change in the update I am working on rn

**Comment by Bris42** [comment]
I did! Unless you mean the games settings and not Mixtape's settings.

**Comment by AliahX** [comment]
Could you include a screenshot of ur debug screen?

**Comment by Bris42** [comment]
Yeah! Just uh... tell me how to do that, if you dont mind. I'm new to the whole pc gaming thing

**Comment by AliahX** [comment]
You just need to be in-game and press f3!

**Comment by Bris42** [comment]
![2024-01-30_05 06 45](https://github.com/AliahX/Mixtape/assets/158150027/c1d9e441-0d1d-455e-bc55-4f7651380294)
Here you go, hope that helps.

**Comment by AliahX** [comment]
Everything looks all correct there. If u were to press the skip button, mixtape would still make you wait the full time until the next song, because you haven't set the times individually for each music type. I would recommend setting the delays to 0 if you want music to constantly happen.

**Comment by Bris42** [comment]
That got it working! Thank you, I guess the problem was just me all along. Sorry about that. Just curious, are the numbers set to ticks, or seconds?

**Comment by AliahX** [comment]
They're ticks!
Its not ur fault 😭 I just didn't make it very obvious how it all works. In the later versions there's a toggle in the main config tab that lets u turn of delays on all of them which makes it more understandable.

**Comment by Bris42** [comment]
That's fair. But issues aside, I just wanted to say how great this mod is. I spent like, 20 minutes searching for something that would allow me to control how often the music plays, and I was surprised by how few mods actually bothered with the music at all. So thanks for making this, its great so far. Definitely one of the few I'll keep up with.
