### ISSUE TITLE
[Suggestion] Delay before starting a disc

### ISSUE THREAD

**Issue by MidyGamy** [UnJust1ce/Mixtape#22]
To improve the Jukebox, why not add a delay for the disc to start and notice the general music fade (kinda like Legacy Editions of Minecraft)

**Comment by AliahX** [comment]
A delay on the start of disk would cause the audio to be out of sync with the actual jukebox, bc the jukebox has data inside of it on how many ticks the song has been playing for and which song, which would muck up when redstone detects it finishing.
