### ISSUE TITLE
[1.19.4] Built-in resource packs are incompatible with MC 1.19.4

### ISSUE THREAD

**Issue by Sw3et-Dre4mer** [UnJust1ce/Mixtape#3]
In Mixtape 1.3.2, the built-in resource packs are incompatible with MC 1.19.4 due to the old `pack_format` value in `pack.mcmeta`.
This can be fixed by updating the value from `12` to `13`.

![2023-04-10_14 54 41](https://user-images.githubusercontent.com/81977006/230837354-b0d745bd-ae57-4137-9311-e3fb76fc7ce6.png)

**Comment by AliahX** [comment]
Thanks for letting me know! I forgot to do that when porting it, ill do that now.

**Comment by AliahX** [comment]
done! https://github.com/AliahX/Mixtape/releases/tag/v1.3.3
