### ISSUE TITLE
Minecraft crashes sometimes when trying to show toast message

### ISSUE THREAD

**Issue by MrRomainzZ** [UnJust1ce/Mixtape#6]
This crash message shows up. According to first line, I guess it is trying to get the name of a specific song but can't. Also toast message appears for some songs without crashing the game

![image](https://github.com/AliahX/Mixtape/assets/47046463/ebb6b0a0-85f4-4822-bff8-c2faf6aa3d25)

**Comment by AliahX** [comment]
Thanks for letting me know! Have you added any custom songs (outside of the mixtape ones) or was it trying to play a vanilla song?

**Comment by MrRomainzZ** [comment]
Oh, I haven't thought about this one. I actually have a resourcepack with custom music. I'll try to play for some time without it to see if problem still exists

**Comment by AliahX** [comment]
that would almost definitely be causing it. could you send me a link to the resourcepack? I can try modify it so that it works with mixtape

**Comment by MrRomainzZ** [comment]
I've spammed to play new song for some time. Doesn't seem to crash. So it can't take name of resourcepack's songs

**Comment by MrRomainzZ** [comment]
> that would almost definitely be causing it. could you send me a link to the resourcepack? I can try modify it so that it works with mixtape

https://dropmefiles.com/QLI39

**Comment by AliahX** [comment]
Hey, i'm not able to download the zip file from that website. every time i click download the page refreshes. could you try drag it directly into the text box here to upload it?

**Comment by MrRomainzZ** [comment]
It says that archive is too big. It's 51 MB but I have a limit of 25 MB. Wait a second. I'll upload it to a better website

**Comment by MrRomainzZ** [comment]
I hope this works

https://drive.google.com/file/d/1tEiFTvkGiTit5hyRMwTiCoQDzESluIB0/view?usp=drive_link

**Comment by AliahX** [comment]
you will need to change sharing permissions for me to view it

**Comment by MrRomainzZ** [comment]
Sorry and try it again

**Comment by AliahX** [comment]
Thanks! ill try make it compatible now!

**Comment by AliahX** [comment]
Mixtape actually already has a built-in version of your resourcepack lol. Its called unused_music, and you can use it instead of your own one because it is already compatible

**Comment by MrRomainzZ** [comment]
Ok. Thank you!

**Comment by AliahX** [comment]
I will be making a quick update that stops the game from crashing when you use a music resourcepack with it as well
