### ISSUE TITLE
Mod plays creative music in multiplayer survival even when it is toggled off

### ISSUE THREAD

**Issue by MrRomainzZ** [UnJust1ce/Mixtape#7]
It works fine in singleplayer though (I also ran into issue with skipping or playing new music via hotkeys but I think it should be addressed in another issue)

https://youtu.be/7_nok-E30XQ

**Comment by AliahX** [comment]
Wow, thanks for letting me know! it might be easier if we talk abt the issues on the discord server just bc its better for messaging.
